"""add_ai_analysis

Revision ID: 7dda21aa7971
Revises: aa7bc84e01e8
Create Date: 2026-02-20 20:44:32.620668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dda21aa7971'
down_revision: Union[str, Sequence[str], None] = 'aa7bc84e01e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controls', sa.Column('ai_analysis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controls', 'ai_analysis')
    # ### end Alembic commands ###
