"""fix_control_model_cleanup

Revision ID: ee56b74bcdb7
Revises: b4a8b598e9ce
Create Date: 2026-02-21 03:08:22.735294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee56b74bcdb7'
down_revision: Union[str, Sequence[str], None] = 'b4a8b598e9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('controls', 'status',
               existing_type=postgresql.ENUM('IMPLEMENTED', 'PARTIAL', 'MISSING', name='controlstatus'),
               type_=sa.Enum('IMPLEMENTED', 'PARTIAL', 'MISSING', name='control_status'),
               nullable=False)
    op.alter_column('controls', 'risk_score',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='controlrisk'),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='control_risk'),
               nullable=False)
    op.alter_column('controls', 'compliance_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('controls', 'compliance_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('controls', 'risk_score',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='control_risk'),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='controlrisk'),
               nullable=True)
    op.alter_column('controls', 'status',
               existing_type=sa.Enum('IMPLEMENTED', 'PARTIAL', 'MISSING', name='control_status'),
               type_=postgresql.ENUM('IMPLEMENTED', 'PARTIAL', 'MISSING', name='controlstatus'),
               nullable=True)
    # ### end Alembic commands ###
